global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'monero-marketplace'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load alert rules
rule_files:
  - '/etc/prometheus/alerts/*.yml'

# Scrape configurations
scrape_configs:
  # ============================================================================
  # Application Server
  # ============================================================================
  - job_name: 'marketplace-server'
    static_configs:
      - targets: ['server:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # ============================================================================
  # Monero Wallet RPC - Removed (no /metrics endpoint)
  # ============================================================================
  # NOTE: Monero wallet RPC does not expose Prometheus metrics natively.
  # To monitor Monero wallets, you need to:
  # 1. Create a custom exporter that calls get_balance, get_height, etc.
  # 2. Export those values as Prometheus metrics
  # 3. Add the exporter as a scrape target here
  #
  # Example implementation: monero-exporter service (to be implemented)

  # ============================================================================
  # Node Exporter - System Metrics
  # ============================================================================
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']
    scrape_interval: 15s

  # ============================================================================
  # Monero Wallet Exporter - Wallet Metrics
  # ============================================================================
  - job_name: 'monero-wallets'
    static_configs:
      - targets: ['monero-exporter:9101']
    scrape_interval: 30s

  # ============================================================================
  # Prometheus Self-Monitoring
  # ============================================================================
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
